- name: 'run apt update'
  apt:
    name: '*'
    state: latest

- name: "install nginx"
  package:
    name: nginx
    state: present

- name: "net-tools"
  package:
    name: net-tools
    state: present